# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath S:/360Downloads/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir S:/360Downloads/Pipeline/Pipeline.cache/wt [current_project]
set_property parent.project_path S:/360Downloads/Pipeline/Pipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files S:/360Downloads/Pipeline/test.coe
add_files S:/360Downloads/Pipeline/dmem.coe
add_files s:/360Downloads/Pipeline/text2.coe
add_files -quiet S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/instructionROM/instructionROM.dcp
set_property used_in_implementation false [get_files S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/instructionROM/instructionROM.dcp]
add_files -quiet s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM.dcp
set_property used_in_implementation false [get_files s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM.dcp]
add_files -quiet s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/clk_div/clk_div.dcp
set_property used_in_implementation false [get_files s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/clk_div/clk_div.dcp]
read_verilog -library xil_defaultlib {
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/full_adder.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/adder_4bits.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/mux_adder.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/adder_32bits.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/Zero_test.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/RsSel_RtSel.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/Registers.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/Hazard_detector.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/ff_lib.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/Decode.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/ALU.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/seg.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/IF.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/ID.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/EX.v
  S:/360Downloads/Pipeline/Pipeline.srcs/sources_1/new/MipsPipelineCPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc S:/360Downloads/Pipeline/Pipeline.srcs/constrs_1/new/ppp.xdc
set_property used_in_implementation false [get_files S:/360Downloads/Pipeline/Pipeline.srcs/constrs_1/new/ppp.xdc]


synth_design -top MipsPipelineCPU -part xc7a100tcsg324-1


write_checkpoint -force -noxdef MipsPipelineCPU.dcp

catch { report_utilization -file MipsPipelineCPU_utilization_synth.rpt -pb MipsPipelineCPU_utilization_synth.pb }
