# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM.xci
# IP: The module: 'dataRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM.xci
# IP: The module: 'dataRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: s:/360Downloads/Pipeline/Pipeline.srcs/sources_1/ip/dataRAM/dataRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
